# Default Values for Helm Chart

container:
	webAppImage: nginx
	webAppPort : 80
	probePort  : 10000
	initTime   : 10 
	readinessProbePeriod: 10
	livenessProbePeriod : 20
	livenessProbeDelay  : 15
hpa:
	minRepl : 2
	maxRepl : 4
	
service:
	type            : LoadBalancer
	loadBalancerPort: 7777	
	protocol        : TCP
