# Default Values for Helm Chart

container:
  webAppImage: nginx
  webAppPort : 80
  probePort  : 10000
  initTime   : 10
  cpuLimit     : "300m"
  memoryLimit  : "128M"
  cpuRequest   : "100m" #0.1CPU
  memoryRequest: "128M"
  readinessProbePeriod: 15
  livenessProbePeriod : 20
  livenessProbeDelay  : 25
hpa:
  minRepl : 2
  maxRepl : 4
  cpuUtilization   : 80
  memoryUtilization: 90

service:
  type            : LoadBalancer
  loadBalancerPort: 7777
  protocol        : TCP
