apiVersion : apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web-app
  labels:
    app: {{ .Release.Name }}-deployment
    env: test
    owner: anton
spec:
  selector:
    matchLabels:
      project: {{ .Release.Name }}
  minReadySeconds: {{ .Values.container.initTime }} # 10 seconds - app initialize time
  template:
    metadata:
     labels:
      project: {{ .Release.Name }}
    spec:
      affinity:  # Распределение по зонам кластера
       podAntiAffinity:
         preferredDuringSchedulingIgnoredDuringExecution:
         - weight: 5
           podAffinityTerm:
             labelSelector:
               matchExpressions:
                 - key: app
                   operator: In
                   values:
                     - {{ .Release.Name }}-web-app
             topologyKey: topology.kubernetes.io/zone # Распределение по зонам кластера
      containers:
        - name: {{ .Release.Name }}-container
          image: {{ .Values.container.webAppImage }}
          resources:
            limits:
              cpu: {{ .Values.container.cpuLimit }} # 0.3 CPU (значительно больше для первых запросов)
              memory: {{ .Values.container.memoryLimit }} #128M
            requests:
              cpu: {{ .Values.container.cpuRequest }} # 0.1 CPU
              memory: {{ .Values.container.memoryRequest }} #128M
          ports:
            - containerPort: {{ .Values.container.webAppPort }}
            - containerPort: {{ .Values.container.probePort }} # Порт для проб
          readinessProbe:
            tcpSocket:
              port: {{ .Values.container.probePort }}
            initialDelaySeconds: {{ .Values.container.initTime }} # 10 seconds - app initialize time
            periodSeconds: {{ .Values.container.readinessProbePeriod }} 
          livenessProbe:
            tcpSocket:
              port: {{ .Values.container.probePort }}
            initialDelaySeconds: {{ .Values.container.livenessProbeDelay }}
            periodSeconds: {{ .Values.container.livenessProbePeriod }}
