apiVersion : apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: {{ .Release.Name }}-deployment
    env: test
    owner: anton
spec:
  selector:
    matchLabels:
      project: {{ .Release.Name }}
  minReadySeconds: {{ .Values.container.initTime }}
  template:
    metadata:
     labels: 
      project: {{ .Release.Name }}
    spec:
     containers:
       - name: {{ .Release.Name }}-container
         image: {{ .Values.container.webAppImage }}
         ports: 
            - containerPort: {{ .Values.container.webAppPort }}
	    - containerPort: {{ .Values.container.probePort }}
	 readinessProbe:
	 	tcpSocket:
	 		port: {{ .Values.container.probePort }}
	 	initialDelaySeconds: {{ .Values.container.initTime }}
	 	periodSeconds: {{ Values.container.readinessProbePeriod }}
	 livenessProbe:
	 	tcpSocket:
	 		port: {{ .Values.container.probePort }}
	 	initialDelayseconds: {{ .Values.container.livenessProbeDelay }}
	 	periodSeconds: {{ .Values.container.livenessProbePeriod }}

