apiVersion : apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: {{ .Release.Name }}-deployment
    env: test
    owner: anton
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      project: {{ .Release.Name }}
  template:
    metadata:
     labels: 
      project: {{ .Release.Name }}
    spec:
     containers:
       - name: {{ .Release.Name }}-container
         image: {{ .Values.container.webAppImage }}
         ports: 
            - containerPort: {{ .Values.container.webAppPort }}


