apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    env: test
    owner: anton
spec:
  type: {{ .Values.service.type }}
  selector:
    project: {{ .Release.Name }}
  ports:
   - name: {{ .Release.Name }}-port
     protocol: {{ .Values.service.protocol }}
     port: {{ .Values.service.loadBalancerPort }}
     targetPort: {{ .Values.container.webAppPort }}
